<?xml version="1.0"?>
<robot name="curiosity_rover" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="ll" value="link_left"/>
<xacro:property name="lr" value="link_right"/>
<xacro:property name="roboname" value="curiosity_rover"/>

<xacro:property name="base_length" value="2.7"/>
<xacro:property name="base_width" value="5"/>
<xacro:property name="base_height" value="1"/>

<xacro:property name="base_x" value="0"/>
<xacro:property name="base_y" value="0"/>
<xacro:property name="base_z" value="2"/>

<!--Base link-->
<link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="${base_x} ${base_y} ${base_z}"/>
      <material name="white">
      	<color rgba="1 1 1 1"/>
      </material>
    </visual>
</link>
<!-- Camera_base-to-Base -->
<link name="link_camera_base">
	<visual>
		<geometry>
			<cylinder length="2" radius=".2"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<material name="white">
			<color rgba="1 1 0 1"/>
		</material>


	</visual>
</link>
<joint name="joint_camera_base" type="fixed">
	<parent link="base_link"/>
	<child link="link_camera_base"/>
	<origin xyz="0 0 ${base_height + base_z}" />
</joint>

<!-- Camera_base-to-Camera_holder -->
<link name="link_camera_holder">
	<visual>
		<geometry>
			<cylinder length=".5" radius=".1"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</visual>
</link>
<joint name="joint_camera_holder" type="continuous">
	<parent link="link_camera_base"/>
	<child link="link_camera_holder"/>
	<origin xyz="0 0 1"/>
	<axis xyz="0 0 1"/>
</joint>


<!-- Camer_holder-to-Camera -->
<link name="link_camera">
	<visual>
		<geometry>
			<box size=".4 .2 .1"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</visual>
</link>
<joint name="joint_camera" type="fixed">
	<parent link="link_camera_holder"/>
	<child link="link_camera"/>
	<origin xyz="0 0 .2"/>
</joint>


<!-- base-to-right wheel -->
<link name="${lr}_front">
	<visual>
		<geometry>
			<cylinder length="3" radius=".1"/>
		</geometry>
		<origin xyz=".1 0.5 -${base_height/2}" rpy="1.3 0 -0.6"/>
	</visual>
</link>
<joint name="joint_${lr}_front" type="fixed">
	<parent link="base_link"/>
	<child link="${lr}_front"/>
	<origin xyz="${base_length/2} 0 ${base_z}"/>
</joint>


<!-- wheel -->
<link name="wheel">
	<visual>
		<geometry>
			<cylinder length="1" radius="1"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 1.57 0"/>
		<material name="white"/>
	</visual>
</link>
<joint name="joint_wheel" type="fixed">
	<parent link="${lr}_front"/>
	<child link="wheel"/>
	<origin xyz="${base_length/2} ${base_width/2-.5} -1"/>
</joint>

<!-- ************************ -->
<!-- base-to-right wheel -->
<link name="${ll}_front">
	<visual>
		<geometry>
			<cylinder length="3" radius=".1"/>
		</geometry>
		<origin xyz="-.1 .5 -${base_height/2}" rpy="1.3 0 0.6"/>
	</visual>
</link>
<joint name="joint_${ll}_front" type="fixed">
	<parent link="base_link"/>
	<child link="${ll}_front"/>
	<origin xyz="-${base_length/2} 0 ${base_z}"/>
</joint>


<!-- wheel -->
<link name="${ll}_front_wheel">
	<visual>
		<geometry>
			<cylinder length="1" radius="1"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 -1.57 0"/>
		<material name="white"/>
	</visual>
</link>
<joint name="${ll}_joint_wheel" type="continuous">
	<parent link="${ll}_front"/>
	<child link="${ll}_front_wheel"/>
	<origin xyz="-${base_length/2} ${base_width/2-.5} -1"/>
	<axis xyz="1 0 0"/>
</joint>

<!-- ************************ -->
<!-- base-to-back wheel -->
<xacro:macro name="back_wheel" params="prefix reflect">
	<link name="${prefix}_back">
		<visual>
			<geometry>
				<cylinder length="2" radius=".1"/>
			</geometry>
			<origin xyz="0 0 0" rpy="1.8 0 ${reflect * 0.2}"/>
		</visual>
	</link>

	<joint name="joint_${prefix}_back" type="fixed">
		<parent link="base_link"/>
		<child link="${prefix}_back"/>
		<origin xyz="${reflect*(base_length/2)} -1 ${base_z}"/>
	</joint>

	<link name="${prefix}_back_holder">
		<visual>
			<geometry>
				<cylinder length="1" radius=".2"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 1.57 0"/>
		</visual>
	</link>

	<joint name="joint_${prefix}_back_holder" type="fixed">
		<parent link="base_link"/>
		<child link="${prefix}_back_holder"/>
		<origin xyz="${reflect*(base_length/2)} -2 ${base_z-.2}"/>
	</joint>


	<link name="${prefix}_back_rot">
		<visual>
			<geometry>
				<cylinder length="1.5" radius=".13"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 1.57 0"/>
		</visual>
	</link>

	<joint name="joint_${prefix}_back_rot" type="continuous">
		<parent link="${prefix}_back_holder"/>
		<child link="${prefix}_back_rot"/>
		<origin xyz="${reflect *0.2} 0 0"/>
		<axis xyz="1 0 0"/>
	</joint>

	<link name="${prefix}_back_pin">
		<visual>
			<geometry>
				<sphere radius="0.14"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 1.57 0"/>
		</visual>
	</link>

	<joint name="joint_${prefix}_back_pin" type="fixed">
		<parent link="${prefix}_back_rot"/>
		<child link="${prefix}_back_pin"/>
		<origin xyz="${reflect *0.2} 0 0"/>
	</joint>

	<link name="${prefix}_mid_bar">
		<visual>
			<geometry>
				<cylinder length="1.3" radius=".1"/>
			</geometry>
			<origin xyz="${reflect*0.2} 0.5 -0.3" rpy="1 0 ${reflect*-1*.5}"/>
		</visual>
	</link>

	<joint name="joint_${prefix}_mid_bar" type="fixed">
		<parent link="${prefix}_back_rot"/>
		<child link="${prefix}_mid_bar"/>
		<origin xyz="${reflect *0.5} 0 0"/>
	</joint>



<!-- middle wheel -->
<link name="${prefix}_mid_wheel">
	<visual>
		<geometry>
			<cylinder length="1" radius="1"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 -1.57 0"/>
		<material name="white"/>
	</visual>
</link>
<joint name="${prefix}_mid_wheel" type="continuous">
	<parent link="${prefix}_mid_bar"/>
	<child link="${prefix}_mid_wheel"/>
	<origin xyz="${reflect*.8} .8 -1"/>
	<axis xyz="1 0 0"/>
</joint>


<link name="${prefix}_back_bar">
		<visual>
			<geometry>
				<cylinder length="2" radius=".1"/>
			</geometry>
			<origin xyz="${reflect*0.1} -0.7 -0.5" rpy="-1 0 ${reflect*.5}"/>
		</visual>
	</link>

	<joint name="joint_${prefix}_back_bar" type="fixed">
		<parent link="${prefix}_back_rot"/>
		<child link="${prefix}_back_bar"/>
		<origin xyz="${reflect *0.8} 0 0"/>
	</joint>


	<!-- back wheel -->
<link name="${prefix}_back_wheel">
	<visual>
		<geometry>
			<cylinder length="1" radius="1"/>
		</geometry>
		<origin xyz="0 0 0" rpy="0 -1.57 0"/>
		<material name="white"/>
	</visual>
</link>
<joint name="${prefix}_back_wheel" type="continuous">
	<parent link="${prefix}_back_bar"/>
	<child link="${prefix}_back_wheel"/>
	<origin xyz="${reflect* 1.0} -2 -1"/>
	<axis xyz="1 0 0"/>
</joint>

</xacro:macro>

<xacro:back_wheel prefix="right" reflect="1"/>
<xacro:back_wheel prefix="left" reflect="-1"/>
</robot>
	